# Generated by Django 4.2.5 on 2023-10-01 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Наименование')),
                ('description', models.CharField(max_length=250, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Product/', verbose_name='Изображение')),
                ('category', models.CharField(max_length=100, verbose_name='Категории')),
                ('price', models.IntegerField(max_length=100, verbose_name='Цена')),
                ('data_creation', models.DateField(blank=True, null=True, verbose_name='Дата создания')),
                ('data_change', models.DateTimeField(blank=True, null=True, verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name': 'Продукт',
            },
        ),
    ]
