# Generated by Django 4.2.5 on 2023-10-01 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
    ]
