# Generated by Django 4.2.5 on 2023-10-01 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_product_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
    ]
